# Generated by Django 6.0.1 on 2026-01-07 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groupes', '0001_initial'),
        ('inscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joues', models.PositiveSmallIntegerField(default=0)),
                ('gagnes', models.PositiveSmallIntegerField(default=0)),
                ('perdus', models.PositiveSmallIntegerField(default=0)),
                ('egalites', models.PositiveSmallIntegerField(default=0)),
                ('points_marques', models.PositiveSmallIntegerField(default=0)),
                ('points_encaisses', models.PositiveSmallIntegerField(default=0)),
                ('difference', models.SmallIntegerField(default=0)),
                ('points_classement', models.SmallIntegerField(default=0)),
                ('maj_le', models.DateTimeField(auto_now=True)),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classements', to='inscriptions.equipe')),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classements', to='groupes.groupe')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('groupe', 'equipe'), name='unique_classement_par_groupe_equipe')],
            },
        ),
    ]
