# Generated by Django 6.0.1 on 2026-01-08 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classements", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="classement",
            name="note_admin",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="classement",
            name="rang_manuel",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
