# Generated by Django 6.0.1 on 2026-03-31 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("matchs", "0001_initial"),
        ("phases", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Creneau",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("index", models.PositiveIntegerField()),
                ("debut", models.DateTimeField()),
                ("duree_minutes", models.PositiveSmallIntegerField(default=15)),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="creneaux",
                        to="core.edition",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PausePlanning",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nom", models.CharField(max_length=80)),
                ("debut", models.DateTimeField()),
                ("duree_minutes", models.PositiveSmallIntegerField()),
                ("est_active", models.BooleanField(default=True)),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pauses_planning",
                        to="core.edition",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Terrain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nom", models.CharField(max_length=40)),
                (
                    "type_terrain",
                    models.CharField(
                        choices=[("INTERIEUR", "Intérieur"), ("EXTERIEUR", "Extérieur")],
                        max_length=10,
                    ),
                ),
                ("ordre", models.PositiveSmallIntegerField(default=0)),
                ("est_actif", models.BooleanField(default=True)),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="terrains",
                        to="core.edition",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlanningSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "type_slot",
                    models.CharField(
                        choices=[("MATCH", "Match"), ("CONCOURS_SHOOT", "Concours de shoot")],
                        max_length=32,
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                (
                    "creneau",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slots",
                        to="planning.creneau",
                    ),
                ),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="planning_slots",
                        to="core.edition",
                    ),
                ),
                (
                    "match",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="planning_slot",
                        to="matchs.match",
                    ),
                ),
                (
                    "phase_globale",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="planning_slots",
                        to="phases.phaseglobale",
                    ),
                ),
                (
                    "sous_phase",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="planning_slots",
                        to="phases.sousphase",
                    ),
                ),
                (
                    "terrain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="slots",
                        to="planning.terrain",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="creneau",
            constraint=models.UniqueConstraint(
                fields=("edition", "index"), name="unique_creneau_par_edition_index"
            ),
        ),
        migrations.AddConstraint(
            model_name="pauseplanning",
            constraint=models.UniqueConstraint(
                fields=("edition", "debut"), name="unique_pause_par_edition_debut"
            ),
        ),
        migrations.AddConstraint(
            model_name="terrain",
            constraint=models.UniqueConstraint(
                fields=("edition", "nom"), name="unique_terrain_par_edition_nom"
            ),
        ),
        migrations.AddIndex(
            model_name="planningslot",
            index=models.Index(
                fields=["edition", "type_slot"], name="planning_pl_edition_2c8a56_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="planningslot",
            index=models.Index(
                fields=["edition", "phase_globale"], name="planning_pl_edition_66994a_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="planningslot",
            constraint=models.UniqueConstraint(
                fields=("creneau", "terrain"), name="unique_slot_par_creneau_et_terrain"
            ),
        ),
        migrations.AddConstraint(
            model_name="planningslot",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("match__isnull", False), ("type_slot", "MATCH")),
                    models.Q(("match__isnull", True), ("type_slot", "CONCOURS_SHOOT")),
                    _connector="OR",
                ),
                name="check_slot_type_vs_match",
            ),
        ),
    ]
