# Generated by Django 6.0.1 on 2026-01-07 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Creneau",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("index", models.PositiveIntegerField()),
                ("debut", models.DateTimeField()),
                ("duree_minutes", models.PositiveSmallIntegerField(default=15)),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="creneaux",
                        to="core.edition",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("edition", "index"), name="unique_creneau_par_edition_index"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Terrain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nom", models.CharField(max_length=40)),
                (
                    "type_terrain",
                    models.CharField(
                        choices=[("INTERIEUR", "Intérieur"), ("EXTERIEUR", "Extérieur")],
                        max_length=10,
                    ),
                ),
                ("ordre", models.PositiveSmallIntegerField(default=0)),
                ("est_actif", models.BooleanField(default=True)),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="terrains",
                        to="core.edition",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("edition", "nom"), name="unique_terrain_par_edition_nom"
                    )
                ],
            },
        ),
    ]
