# Generated by Django 6.0.1 on 2026-01-11 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("matchs", "0008_match_vainqueur"),
        ("phases", "0001_initial"),
        ("planning", "0002_pauseplanning"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanningSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "type_slot",
                    models.CharField(
                        choices=[("MATCH", "Match"), ("CONCOURS_SHOOT", "Concours de shoot")],
                        max_length=32,
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                (
                    "creneau",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slots",
                        to="planning.creneau",
                    ),
                ),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="planning_slots",
                        to="core.edition",
                    ),
                ),
                (
                    "match",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="planning_slot",
                        to="matchs.match",
                    ),
                ),
                (
                    "phase_globale",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="planning_slots",
                        to="phases.phaseglobale",
                    ),
                ),
                (
                    "sous_phase",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="planning_slots",
                        to="phases.sousphase",
                    ),
                ),
                (
                    "terrain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="slots",
                        to="planning.terrain",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("creneau", "terrain"), name="unique_slot_par_creneau_et_terrain"
                    ),
                    models.UniqueConstraint(
                        fields=("edition", "creneau", "terrain"),
                        name="unique_slot_par_edition_creneau_terrain",
                    ),
                ],
            },
        ),
    ]
