# Generated by Django 6.0.1 on 2026-01-12 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("matchs", "0008_match_vainqueur"),
        ("phases", "0001_initial"),
        ("planning", "0003_planningslot"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="planningslot",
            name="unique_slot_par_edition_creneau_terrain",
        ),
        migrations.AddIndex(
            model_name="planningslot",
            index=models.Index(
                fields=["edition", "type_slot"], name="planning_pl_edition_2c8a56_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="planningslot",
            index=models.Index(
                fields=["edition", "phase_globale"], name="planning_pl_edition_66994a_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="planningslot",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("match__isnull", False), ("type_slot", "MATCH")),
                    models.Q(("match__isnull", True), ("type_slot", "CONCOURS_SHOOT")),
                    _connector="OR",
                ),
                name="check_slot_type_vs_match",
            ),
        ),
    ]
