# Generated by Django 6.0.1 on 2026-03-31 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tournoi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("ROOKIE", "Rookie"),
                            ("LOISIR", "Loisir"),
                            ("COMPETITEUR", "Compétiteur"),
                        ],
                        max_length=20,
                    ),
                ),
                ("libelle", models.CharField(blank=True, max_length=64)),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tournois",
                        to="core.edition",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tournoi",
                "verbose_name_plural": "Tournois",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("edition", "code"), name="unique_tournoi_par_edition_et_code"
                    )
                ],
            },
        ),
    ]
