# Generated by Django 6.0.1 on 2026-03-31 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("libelle_equipe_a", models.CharField(blank=True, max_length=255)),
                ("libelle_equipe_b", models.CharField(blank=True, max_length=255)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("A_PLANIFIER", "À planifier"),
                            ("PLANIFIE", "Planifié"),
                            ("TERMINE", "Terminé"),
                            ("FORFAIT_A", "Forfait équipe A"),
                            ("FORFAIT_B", "Forfait équipe B"),
                            ("DOUBLE_FORFAIT", "Double forfait"),
                        ],
                        default="A_PLANIFIER",
                        max_length=20,
                    ),
                ),
                (
                    "tour_finale",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("HUITIEME", "Huitième"),
                            ("QUART", "Quart"),
                            ("DEMI", "Demi"),
                            ("FINALE", "Finale"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("numero_tour", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="MatchSheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("sheet_code", models.CharField(editable=False, max_length=36, unique=True)),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Score",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("points_a", models.PositiveSmallIntegerField()),
                ("points_b", models.PositiveSmallIntegerField()),
                ("valide_le", models.DateTimeField(blank=True, null=True)),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
