# Generated by Django 6.0.1 on 2026-03-31 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("groupes", "0001_initial"),
        ("inscriptions", "0001_initial"),
        ("matchs", "0001_initial"),
        ("phases", "0001_initial"),
        ("planning", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="creneau",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="matchs",
                to="planning.creneau",
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="edition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="matchs",
                to="core.edition",
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="equipe_a",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="matchs_comme_a",
                to="inscriptions.equipe",
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="equipe_b",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="matchs_comme_b",
                to="inscriptions.equipe",
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="groupe",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="matchs",
                to="groupes.groupe",
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="phase_globale",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="matchs",
                to="phases.phaseglobale",
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="sous_phase",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="matchs",
                to="phases.sousphase",
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="terrain",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="matchs",
                to="planning.terrain",
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="vainqueur",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="matchs_gagnes",
                to="inscriptions.equipe",
            ),
        ),
        migrations.AddField(
            model_name="matchsheet",
            name="match",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feuille",
                to="matchs.match",
            ),
        ),
        migrations.AddField(
            model_name="score",
            name="match",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, related_name="score", to="matchs.match"
            ),
        ),
        migrations.AddField(
            model_name="score",
            name="valide_par",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="scores_valides",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="match",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("equipe_a__isnull", True),
                    ("equipe_b__isnull", True),
                    models.Q(("equipe_a", models.F("equipe_b")), _negated=True),
                    _connector="OR",
                ),
                name="match_equipes_differentes_si_deux_equipes_reelles",
            ),
        ),
        migrations.AddConstraint(
            model_name="match",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("equipe_a__isnull", False),
                    ("equipe_b__isnull", False),
                    ("groupe__isnull", False),
                ),
                fields=("groupe", "equipe_a", "equipe_b"),
                name="unique_match_par_groupe_et_paire_ordonne",
            ),
        ),
        migrations.AddConstraint(
            model_name="match",
            constraint=models.UniqueConstraint(
                condition=models.Q(("tour_finale__isnull", False)),
                fields=("phase_globale", "sous_phase", "tour_finale", "numero_tour"),
                name="unique_match_finale_par_tour_numero",
            ),
        ),
    ]
