# Generated by Django 6.0.1 on 2026-01-10 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("groupes", "0001_initial"),
        ("inscriptions", "0001_initial"),
        ("matchs", "0004_score"),
        ("phases", "0001_initial"),
        ("planning", "0002_pauseplanning"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="match",
            name="unique_match_par_groupe_et_paire_ordonne",
        ),
        migrations.AlterField(
            model_name="match",
            name="sous_phase",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="matchs",
                to="phases.sousphase",
            ),
        ),
        migrations.AddConstraint(
            model_name="match",
            constraint=models.UniqueConstraint(
                condition=models.Q(("groupe__isnull", False)),
                fields=("groupe", "equipe_a", "equipe_b"),
                name="unique_match_par_groupe_et_paire_ordonne",
            ),
        ),
    ]
