# Generated by Django 6.0.1 on 2026-01-10 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groupes", "0001_initial"),
        ("matchs", "0005_remove_match_unique_match_par_groupe_et_paire_ordonne_and_more"),
        ("phases", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="groupe",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="matchs",
                to="groupes.groupe",
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="sous_phase",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="matchs",
                to="phases.sousphase",
            ),
        ),
    ]
