# Generated by Django 6.0.1 on 2026-01-11 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("groupes", "0001_initial"),
        ("inscriptions", "0001_initial"),
        ("matchs", "0006_alter_match_groupe_alter_match_sous_phase"),
        ("phases", "0001_initial"),
        ("planning", "0002_pauseplanning"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="numero_tour",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="match",
            name="tour_finale",
            field=models.CharField(
                blank=True,
                choices=[
                    ("HUITIEME", "Huitième"),
                    ("QUART", "Quart"),
                    ("DEMI", "Demi"),
                    ("FINALE", "Finale"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="match",
            constraint=models.UniqueConstraint(
                condition=models.Q(("tour_finale__isnull", False)),
                fields=("phase_globale", "sous_phase", "tour_finale", "numero_tour"),
                name="unique_match_finale_par_tour_numero",
            ),
        ),
    ]
