# Generated by Django 6.0.1 on 2026-01-11 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inscriptions", "0001_initial"),
        ("matchs", "0007_match_numero_tour_match_tour_finale_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="vainqueur",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="matchs_gagnes",
                to="inscriptions.equipe",
            ),
        ),
    ]
