# Generated by Django 6.0.1 on 2026-01-07 12:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120, unique=True)),
                ('date_evenement', models.DateField(unique=True)),
                ('heure_debut', models.TimeField(default=datetime.time(14, 0))),
                ('duree_creneau_minutes', models.PositiveSmallIntegerField(default=15)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Édition',
                'verbose_name_plural': 'Éditions',
            },
        ),
    ]
